language: php

matrix:
  allow_failures:
    - php: 7
  fast_finish: true

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text --coverage-clover coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
